rm ackk.txt
rm excel.txt
rm min.txt
rm ingest_rtt.txt
rm seq_acknum.txt
rm seq_acktime.txt
rm seq_or_ack.txt
rm seq_timestamp.txt
rm seqq.txt
rm tack.txt
rm THIS_minrtt_result.txt
rm THIS_rtt_result.txt
rm timestamp.txt
rm tseq.txt
rm tun0ip_or_ingestip.txt
rm tun0ip.txt
rm vpn_ingest.txt
rm min.txt
rm minrtt_lessthan_zero.txt
rm RTT2_VPN_ingest.ods
